/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    media: Media;
    cases: Case;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    site: Site;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cada linha é uma seção da página, na ordem do site. Abra a seção para editar títulos, textos, botões, links e imagens.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  copy?:
    | {
        key: string;
        label?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        key: string;
        label?: string | null;
        src: string;
        alt?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        key: string;
        label?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * O termo principal que alguém digitaria no Google para encontrar esta página, como "seguro de vida". Não aparece no site: serve para a análise abaixo.
   */
  focusKeyphrase?: string | null;
  /**
   * Sem o nome do site: ele é acrescentado automaticamente, conforme "Configurações do site".
   */
  title: string;
  description?: string | null;
  /**
   * Prévia desta página ao compartilhar o link no WhatsApp, LinkedIn ou Facebook. Tamanho ideal: 1200 × 630 px. Sem seleção, usa a imagem padrão de "Configurações do site".
   */
  featuredImage?: (number | null) | Media;
  status?: ('published' | 'draft') | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Crie e edite os artigos do blog. Salvar rascunho guarda sem mudar o site; Publicar coloca o post no ar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Título de destaque: aparece no card do blog e no topo do artigo.
   */
  title: string;
  /**
   * Aparece no card do blog, no topo do artigo e ao compartilhar o link. Use uma imagem horizontal, de preferência 1200 × 675 px.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Use Título 2 e Título 3 para dividir o texto em partes. Imagens podem ser inseridas pelo botão + ou digitando /.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Uma ou duas frases sobre o post. Usado como descrição no Google quando a aba SEO está vazia.
   */
  excerpt?: string | null;
  /**
   * O termo principal que alguém digitaria no Google para encontrar este post. Não aparece no site: serve para a análise abaixo.
   */
  focusKeyphrase?: string | null;
  /**
   * Opcional. Sem preencher, usa o título do post. O nome do site é acrescentado automaticamente.
   */
  seoTitle?: string | null;
  /**
   * Opcional. Sem preencher, usa o resumo.
   */
  seoDescription?: string | null;
  /**
   * Gerado pelo título ao criar. Evite mudar depois de divulgar o link.
   */
  slug: string;
  /**
   * Com data futura, o post só aparece no site a partir dela.
   */
  publishedAt: string;
  category: number | Category;
  authorName: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Assuntos dos posts. Aparecem no filtro da página do blog e na etiqueta de cada card.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Gerado pelo nome ao criar.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  titulo: string;
  parceiro: string;
  segmento: 'fintechs' | 'varejo' | 'rh' | 'corretoras';
  resumo: string;
  /**
   * Define o endereço do case.
   */
  slug: string;
  desafio: string;
  solucao: string;
  produtos?:
    | {
        nome: string;
        id?: string | null;
      }[]
    | null;
  resultados?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  depoimento?: {
    texto?: string | null;
    autor?: string | null;
    cargo?: string | null;
  };
  media?: (number | null) | Media;
  /**
   * Usada quando não há imagem da biblioteca.
   */
  imagem: string;
  destaque?: boolean | null;
  aprovado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  images?:
    | T
    | {
        key?: T;
        label?: T;
        src?: T;
        alt?: T;
        media?: T;
        id?: T;
      };
  links?:
    | T
    | {
        key?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  focusKeyphrase?: T;
  title?: T;
  description?: T;
  featuredImage?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  content?: T;
  excerpt?: T;
  focusKeyphrase?: T;
  seoTitle?: T;
  seoDescription?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  authorName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  titulo?: T;
  parceiro?: T;
  segmento?: T;
  resumo?: T;
  slug?: T;
  desafio?: T;
  solucao?: T;
  produtos?:
    | T
    | {
        nome?: T;
        id?: T;
      };
  resultados?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  depoimento?:
    | T
    | {
        texto?: T;
        autor?: T;
        cargo?: T;
      };
  media?: T;
  imagem?: T;
  destaque?: T;
  aprovado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Nome, logo, ícone e informações padrão de busca e compartilhamento, válidos para o site inteiro.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Entra no título de todas as páginas: "Blog | EQ Seguros". Na página inicial vem primeiro: "EQ Seguros | …".
   */
  siteName: string;
  /**
   * PNG com fundo transparente. Sem seleção, fica o logo atual. Tem prioridade sobre a imagem do logo em "Cabeçalho e rodapé".
   */
  logo?: (number | null) | Media;
  /**
   * Aparece na aba do navegador e nos favoritos. Use uma imagem quadrada em PNG, de preferência 512 × 512 px. Sem seleção, fica o símbolo da EQ.
   */
  favicon?: (number | null) | Media;
  /**
   * Usada no Google e nas redes quando a página não tem descrição própria. Cada página tem a sua em "SEO e publicação".
   */
  defaultDescription?: string | null;
  /**
   * Prévia que aparece ao enviar um link do site no WhatsApp, LinkedIn ou Facebook. Tamanho ideal: 1200 × 630 px.
   */
  shareImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  copy?:
    | {
        key: string;
        label?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        key: string;
        label?: string | null;
        src: string;
        alt?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        key: string;
        label?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  bootstrapComplete?: boolean | null;
  blogBootstrapComplete?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  defaultDescription?: T;
  shareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  images?:
    | T
    | {
        key?: T;
        label?: T;
        src?: T;
        alt?: T;
        media?: T;
        id?: T;
      };
  links?:
    | T
    | {
        key?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  bootstrapComplete?: T;
  blogBootstrapComplete?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}